aap_data/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'aap_data.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('electoral_data.urls')),
    url(r'^login/$', 'django.contrib.auth.views.login',name="my_login"),
)

electoral_data/urls.py
from django.conf.urls import patterns, url

from electoral_data import views

urlpatterns = patterns('',
	# ex: /view/
    url(r'^$', views.index, name='index'),
    # ex: /view/ls
    url(r'^ls/$', views.ls, name='loksabha'),
    # ex: /view/assembly/5
    url(r'^assembly/(?P<ls_id>\d+)/$', views.assembly, name='assembly'),
    # ex: /view/polling/31
    url(r'^polling/(?P<assembly_id>\w+)/$', views.polling, name='polling'),
     # ex: /view/part/31
    url(r'^part/(?P<polling_station_id>\w+)/$', views.part, name='part'),
    # ex: /view/citizens/192
    url(r'^citizens/(?P<part_no>\w+)/(?P<polling_station_id>\w+)/$', views.citizens, name='citizens'),
    # ex: /view/detail/192
    url(r'^detail/(?P<citizen_id>\d+)/$', views.detail, name='detail'),
)

electoral_data/models.py
from django.db import models
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.db.models.signals import post_save


# Create your models here.
class LokSabhaSeat(models.Model):
	name = models.CharField(max_length=100)
	def __unicode__(self):
		return self.name

class AssemblyConstituency(models.Model):
	lok_sabha_seat = models.ForeignKey(LokSabhaSeat)
	name = models.CharField(max_length=100)
	constituency_no = models.CharField('constituency number',max_length=10,primary_key=True)
	def __unicode__(self):
		return self.name + ', ' + self.constituency_no

class PollingStation(models.Model):
	name = models.CharField(max_length=255)
	address = models.CharField(max_length=255,default='')
	constituency = models.ForeignKey(AssemblyConstituency)
	processed = models.BooleanField(default=False)
	def __unicode__(self):
		return self.name

class Citizen(models.Model):
	polling_station = models.ForeignKey(PollingStation)
	part_no = models.IntegerField(blank=False)
	serial_no = models.IntegerField(blank=False)
	voter_id = models.CharField(max_length=100,default='')
	first_name = models.CharField(max_length=100,default='')
	last_name = models.CharField(max_length=100,default='')
	parent_name = models.CharField(max_length=100)
	house_no = models.CharField(max_length=100,default='')
	age = models.IntegerField(default=0)
	SEX_CHOICES = (('male','Male'),('female','Female'))
	sex = models.CharField(max_length=10,choices=SEX_CHOICES,default='male')

	INTEREST_CHOICES = (
		('aap','AAP'),
		('congress','Congress'),
		('ncp','NCP'),
		('bjp','BJP'),
		('shs','SHS'),
		('mns','MNS'),
		('rpi','RPI'),
		('other','Other'),
	)
	interest = models.CharField(max_length=10,choices=INTEREST_CHOICES,default='other')

	PHOTO_CHOICES = (
		('y','Yes'),
		('n','No')
	)
	processed = models.BooleanField(default=False)

	isMember = models.BooleanField('Member',default=False)
	member_no = models.CharField(max_length=20,default='',blank=True)
	email_address = models.EmailField(blank=True)

	isVolunteer = models.BooleanField('Volunteer',default=False)

	isDonor = models.BooleanField('Donor',default=False)
	voucher_no = models.CharField(max_length=100,default='',blank=True)
	donation_amount = models.IntegerField(default=0)

	markForDeletion = models.BooleanField('Mark for Deletion',default=False)
	markForTransposition = models.BooleanField('Mark for Transposition',default=False)

	phone_no = models.CharField(max_length=20,default='',blank=True)

	def __unicode__(self):
		return self.first_name + ', ' + self.last_name

class CitizenInterestForm(ModelForm):
	class Meta:
		model = Citizen
		fields = ['interest', 'processed','isMember','isVolunteer','isDonor','voucher_no','donation_amount','markForTransposition','markForDeletion','phone_no','member_no','email_address']

class UserProfile(models.Model):
	user = models.OneToOneField(User)
	polling_station = models.ForeignKey(PollingStation,blank=True,null=True)
	assembly = models.ForeignKey(AssemblyConstituency,blank=True,null=True)

	def __unicode__(self):
		return 'Test'

electoral_data/views.py
from django.shortcuts import render, redirect
from electoral_data.models import LokSabhaSeat,AssemblyConstituency,PollingStation,Citizen,CitizenInterestForm
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.views.decorators.csrf import csrf_protect
from django.db.models import Count

# Create your views here.
@login_required()
def index(request):
	if request.user.is_staff:
		return redirect(reverse('admin:index'))
	else:		
		return redirect(reverse('electoral_data.views.polling',args=[str(request.user.get_profile().polling_station.id)]))

# Show LS seats
@login_required()
def ls(request):
	if request.user.is_staff:
		ls_seats_list = LokSabhaSeat.objects.all()
		context = {'ls_seats_list': ls_seats_list}
		return render(request, 'electoral_data/ls.html', context)
	else:
		return redirect(reverse('electoral_data.views.polling',args=[str(request.user.get_profile().polling_station.id)]))
	
# Show Assembly seats for LS
@login_required()
def assembly(request,ls_id):
	if request.user.is_staff:
		assembly_list = AssemblyConstituency.objects.filter(lok_sabha_seat=ls_id)
		context = {'assembly_list': assembly_list}
		return render(request, 'electoral_data/assembly.html', context)
	else:
		return redirect(reverse('electoral_data.views.polling',args=[str(request.user.get_profile().polling_station.id)]))

# Show Polling booths for the Assembly seat
@login_required()
def polling(request,assembly_id):
	if request.user.is_staff:
		polling_list = PollingStation.objects.filter(constituency=assembly_id)
		context = {'polling_list': polling_list}
		return render(request, 'electoral_data/polling.html', context)
	else:
		return redirect(reverse('electoral_data.views.polling',args=[str(request.user.get_profile().polling_station.id)]))

# Show Parts in the Polling Booth
@login_required()
def part(request,polling_station_id):
	if request.user.is_staff or request.user.get_profile().polling_station.id == polling_station_id:
		part_no_list = Citizen.objects.filter(polling_station=polling_station_id).values('part_no','polling_station').annotate(num_part=Count('part_no'))
		context = {'part_no_list':part_no_list}
		return render(request,'electoral_data/part.html',context)
	else:
		return redirect(reverse('electoral_data.views.polling',args=[str(request.user.get_profile().polling_station.id)]))

# Show Citizens in the Society
@login_required()
def citizens(request,part_no,polling_station_id):
	citizens_list = Citizen.objects.filter(part_no=part_no,polling_station=polling_station_id).order_by('part_no','serial_no')
	context = {'citizens_list': citizens_list,'part_no':part_no}
	return render(request, 'electoral_data/citizen.html', context)


# Show Citizen details
@login_required()
@csrf_protect
def detail(request,citizen_id):
	citizen_details = Citizen.objects.filter(id=citizen_id)
	if request.method == 'POST':
		form = CitizenInterestForm(request.POST, instance=citizen_details[0])
		form.save()
		part_no = citizen_details[0].part_no
		polling_station_id = citizen_details[0].polling_station.id
		return redirect(reverse('electoral_data.views.citizens',args=[part_no,polling_station_id]))
	else:
		form = CitizenInterestForm(instance=citizen_details[0])
		context = {'citizen_details': citizen_details,'form': form}
		return render(request, 'electoral_data/detail.html', context)
		
	

electoral_data/templates/electoral_data/assembly.html
{% include "electoral_data/header.html" %}
<div class="alert alert-info">
    <p>Choose the Assembly Constituency below</p>
</div>
<div class="container">
	<div class="row">
		<div class="list-group">
			{% if assembly_list %}
			    {% for AssemblyConstituency in assembly_list %}
			        <a href="{% url 'electoral_data.views.polling' AssemblyConstituency.constituency_no %}" class="list-group-item">{{ AssemblyConstituency.name | title}} <span class="glyphicon glyphicon-chevron-right pull-right"></span></a>
			    {% endfor %}
			{% else %}
			    	<p>No LS seats are available.</p>
			{% endif %}
		</div>
	</div>
</div>
{% include "electoral_data/footer.html" %}

electoral_data/templates/electoral_data/citizen.html
{% include "electoral_data/header.html" %}
<div class="alert alert-info">
    <p>Here are the citizen details</p>
</div>
{% if citizens_list %}
<div class="table">
	<table class = "table table-bordered table-hover">
		<thead>
			<tr>
				<th>Part No</th>
				<th>Serial No</th>
				<th>First Name</th>
				<th>Last Name</th>
			</tr>
		</thead>
		<tbody>
			{% for Citizen in citizens_list %}
				{% if Citizen.processed %}
					<tr class="success clickableRow" href="{% url 'electoral_data.views.detail' Citizen.id %}">
				{% else %}
					<tr class="clickableRow" href="{% url 'electoral_data.views.detail' Citizen.id %}">
				{% endif %}
						<td>
							{{ Citizen.part_no }}
						</td>
						<td>
							{{ Citizen.serial_no }}
						</td>
						<td>
							{{ Citizen.first_name | title }}
						</td>
						<td>
							{{ Citizen.last_name | title }}
						</td>
					</tr>
			{% endfor %}
		</tbody>
	</table>
</div>
<form action="/citizens/{{part_no}}/" method="post" class="form-horizontal" role="form">
	{% csrf_token %}
	<input type="hidden" name="processed" value="1">
	<div class="form-group spacer">
	    <div class="col-sm-offset-5 col-sm-12">
	      <input type="submit" class="btn btn-success btn-lg" value="Mark as done">
	    </div>
	</div>
</form>
{% else %}
   	<p>No LS seats are available.</p>
{% endif %}
{% include "electoral_data/footer.html" %}

electoral_data/templates/electoral_data/detail.html
{% include "electoral_data/header.html" %}
{% if citizen_details %}
	{% for Citizen in citizen_details %}
		<h3>{{Citizen.name | title}}</h3>
		<div class="table-resposive">
			<table class="table table-bordered">
				<thead>
					<th class="active">Serial no</th>
					<th class="active">Part no</th>
					<th class="active">Voter ID</th>
					<th class="active">Age</th>
					<th class="active">Gender</th>
				</thead>
				<tbody>
					<tr>
						<td>{{Citizen.serial_no}}</td>
						<td>{{Citizen.part_no}}</td>
						<td>{{Citizen.voter_id}}</td>
						<td>{{Citizen.age}}</td>
						<td>{{Citizen.sex | title}}</td>
					</tr>
				</tbody>
			</table>
		</div>
		<hr>
		<h4> How does this citizen feel about AAP ? </h4>
		<div class="row">
			<div class="col-sm-12">
				<div class="btn-group btn-group-justified btn-group-lg">
			        <a class="btn btn-default noBackground interestBtn" role="button" id="aapBtn">AAP</a>
			        <a class="btn btn-default noBackground interestBtn" role="button" id="congressBtn">Congress</a>
			        <a class="btn btn-default noBackground interestBtn" role="button" id="ncpBtn">NCP</a>
			        <a class="btn btn-default noBackground interestBtn" role="button" id="bjpBtn">BJP</a>
			        <a class="btn btn-default noBackground interestBtn" role="button" id="shsBtn">SHS</a>
			        <a class="btn btn-default noBackground interestBtn" role="button" id="mnsBtn">MNS</a>
			        <a class="btn btn-default noBackground interestBtn" role="button" id="rpiBtn">RPI</a>
			        <a class="btn btn-default noBackground interestBtn" role="button" id="otherBtn">Other</a>
				</div>
			</div>
		</div>
		<hr>
		<form action="{% url 'electoral_data.views.detail' Citizen.id %}" method="post" class="form-horizontal" role="form">
			{% csrf_token %}
			<h4> Is this citizen already an AAP supporter? </h4>
			<div class="row">
				<div class="col-sm-4">
				    <div class="input-group">
				      <span class="input-group-addon">
				        <!-- <input type="checkbox" name="isMember"> -->
				        {{form.isMember}}
				      </span>
				      <button class="form-control btn btn-default noBackground typeCheck">Member</button>
				    </div>
				</div>
				<div class="col-sm-4">
				    <div class="input-group">
				      <span class="input-group-addon">
				        <!-- <input type="checkbox" name="isDonor"> -->
				        {{form.isDonor}}
				      </span>
				      <button class="form-control btn btn-default noBackground typeCheck">Donor</button>
				    </div>
				</div>
				<div class="col-sm-4">
				    <div class="input-group">
				      <span class="input-group-addon">
				      	{{form.isVolunteer}}
				      </span>
				      <button class="form-control btn btn-default noBackground typeCheck">Volunteer</button>
				    </div>
				</div>
			</div>
			<div class="row">
				<div class="col-sm-4">
					<div id="memberFields">
						<div class="smallspacer">
						    <label for="memberNo">Member no</label>
						    <input type="text" class="form-control" id="memberNo" placeholder="Enter Membership number" name="member_no" value="{{form.member_no.value}}">
						</div>
					    <div class="smallspacer">
					    	<label for="memberEmail">Email address</label>
					        <input type="email" class="form-control" id="memberEmail" placeholder="Enter email" name="email_address" value="{{form.email_address.value}}">
					    </div>
					</div>
				</div>
				<div class="col-sm-4">
				    <div id="donorFields">
						<div class="smallspacer">
						    <label for="voucherNo">Voucher no</label>
						    <input type="text" class="form-control" id="voucherNo" placeholder="Enter Voucher number" name="voucher_no" value="{{form.voucher_no.value}}">
						</div>
					    <div class="smallspacer">
					    	<label for="donorAmount">Amount</label>
					        <input type="text" class="form-control" id="donorAmount" placeholder="Enter amount of money dontaed" name="donation_amount" value="{{form.donation_amount.value}}">
					    </div>
					</div>
				</div>
				<div class="col-sm-4">
				    <div id="volunteerFields">
					</div>
				</div>
			</div>
			<hr>
			<div class="row">
				<div class="col-sm-6">
					<h4> Does the citizen say he's not in the electoral roll? </h4>
					<div class="input-group">
					      <span class="input-group-addon">
					        {{form.markForDeletion}}
					      </span>
					      <button class="form-control btn btn-default noBackground typeCheck markCheck" id="markDel">Mark this user for deletion
					      </button>
					</div>
				</div>
				<div class="col-sm-6">
					<h4> Does the citizen say he's moved to a different electoral roll? </h4>
					<div class="input-group">
					      <span class="input-group-addon">
					        {{form.markForTransposition}}
					      </span>
					      <button class="form-control btn btn-default noBackground typeCheck markCheck" id="markTrans">Mark this user for transposition
					      </button>
					</div>
				</div>
			</div>
			<div class="row smallspacer">
				<div class="col-sm-8 offset-sm-4" id="phoneNoSection">
					<label for="phoneNo">Phone no</label>
					<input type="text" class="form-control" id="phoneNo" placeholder="Enter Phone number" name="phone_no" value="{{form.phone_no.value}}">
				</div>
			</div>
			<input type="hidden" name="interest" value="{{ form.interest.value}}" id="interestInput">
			<input type="hidden" name="processed" value="1">
			<hr>
			<div class="form-group">
			    <div class="col-sm-offset-5 col-sm-12">
			      <input type="submit" class="btn btn-primary btn-lg">
			    </div>
			</div>
		</form>
	{% endfor %}
{% else %}
    <p>Error.</p>
{% endif %}
{% include "electoral_data/footer.html" %}

electoral_data/templates/electoral_data/footer.html
</div> <!-- close the container div -->
<footer>
	<script src="https://code.jquery.com/jquery.js"></script>
	<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
	<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
	  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
	  <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
	<![endif]-->
	<script type="text/javascript">
		jQuery(document).ready(function($) {
	      	
	      	/* Whenever the interest button is clicked, remove the colors and add default */
	      	$(".interestBtn").click(function() {
	      		$(this).removeClass('btn-default');
	            $(this).siblings().each(function(){
	            	$(this).removeClass('btn-success').removeClass('btn-danger').removeClass('btn-info').addClass('btn-default');
	            });
	      	});

	      	/* Individial colors for the interest button are addded here */
	      	$('#aapBtn').click(function() {
	      		$(this).addClass('btn-success');
	      		$('#interestInput').val('aap');
	      	});
	      	$('#congressBtn').click(function() {
	      		$(this).addClass('btn-success');
	      		$('#interestInput').val('congress');
	      	});
	      	$('#ncpBtn').click(function() {
	      		$(this).addClass('btn-success');
	      		$('#interestInput').val('ncp');
	      	});
	      	$('#bjpBtn').click(function() {
	      		$(this).addClass('btn-success');
	      		$('#interestInput').val('bjp');
	      	});
	      	$('#shsBtn').click(function() {
	      		$(this).addClass('btn-success');
	      		$('#interestInput').val('shs');
	      	});
	      	$('#mnsBtn').click(function() {
	      		$(this).addClass('btn-success');
	      		$('#interestInput').val('mns');
	      	});
	      	$('#rpiBtn').click(function() {
	      		$(this).addClass('btn-success');
	      		$('#interestInput').val('rpi');
	      	});
	      	$('#otherBtn').click(function() {
	      		$(this).addClass('btn-success');
	      		$('#interestInput').val('other');
	      	});

	      	/* Whenever a button associated with a check box is clicked, trigger the checkbox as well */
	      	$('.typeCheck').click(function() {
	      		$(this).siblings().children().trigger('click');
	      		return false;
	      	});

	      	/* Utility function used to make justified buttons clickable. 
	      	 * Justified buttons are actually <a> tags
	      	 */ 
	      	$(".clickableRow").click(function() {
	      	      window.document.location = $(this).attr("href");
	      	});

	      	/* This function is used to show the hidden fields for the member, donor and volunteer checkboxes */
	      	$('.typeCheck').siblings().children().each(function(){
	      		$(this).click(function(){
	      			id = $(this).attr('id');
	      			$('#'+id.substr(5).toLowerCase()+'Fields').slideToggle(100);
	      		});
	      		if($(this).attr('checked') == 'checked')
	      		{
	      			id = $(this).attr('id');
	      			$('#'+id.substr(5).toLowerCase()+'Fields').slideToggle(50);
	      		}
	      	});

	      	/* Show the phone number whenever the Deletion or Transposition checkboxes are ticked */
	      	// $('.markCheck').click(function(){
	      	// 	$('#phoneNoSection').slideToggle(100);
	      	// });

	      	/* In value is already there in the db, show the colors for del and trans buttons */
	      	$('.markCheck').each(function(){
	      		node = $(this);
	      		if(node.siblings().children().first().attr('checked') == 'checked')
	      		{
	      			if(node.attr('id') == 'markDel')
	      				node.toggleClass('btn-danger').toggleClass('btn-default')
	      			else
	      				node.toggleClass('btn-warning').toggleClass('btn-default')
	      		}
	      	});

	      	/* If there is already a ticket check box, show the phone no */
	      	// if($('#id_markForDeletion').attr('checked') == 'checked' || $('#id_markForTransposition').attr('checked') == 'checked')
		      // 	{
		      // 		$('#phoneNoSection').slideToggle(50);
		      // 		console.log('test');
		      // 	}

	      	/* Toggle colors for the two Deletion and Transposition checkbox + buttons */
	      	$('#markDel').click(function(){$(this).toggleClass('btn-danger').toggleClass('btn-default')})
	      	$('#markTrans').click(function(){$(this).toggleClass('btn-warning').toggleClass('btn-default')})

	      	/* If a interest is already there in the databse, show that color by default */
	      	$('#{{ form.interest.value }}Btn').trigger('click');

		});
	</script>
</footer>
</body>

electoral_data/templates/electoral_data/header.html
<head>
    <title>AAP Mahrashtra Electoral Data</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
    <!-- <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css"> -->
    <!-- <link rel="stylesheet" href="//bootswatch.com/spacelab/bootstrap.min.css"> -->
    <link rel="stylesheet" href="//bootswatch.com/readable/bootstrap.min.css">
    <!-- <link rel="stylesheet" href="//bootswatch.com/flatly/bootstrap.min.css"> -->
    <!-- <link rel="stylesheet" href="//bootswatch.com/lumen/bootstrap.min.css"> -->
    <style type="text/css">
    	.noBackground {
    		background-image: none;
    	}
    	.spacer {
    		margin-top: 40px;
    	}
        .smallspacer {
            margin-top: 15px;
        }
        #memberFields,#donorFields,#volunteerFields {
            display:none;
        }
        hr {
            margin-top: 24px;
            margin-bottom: 24px;
        }
        .clickableRow {
            cursor: pointer;
        }
    </style>
</head>
<body>
	<div class="container">
		<div class="page-header">
			<h1>AAP Maharashtra Electoral Data tool</h1>
		</div>

electoral_data/templates/electoral_data/ls.html
{% include "electoral_data/header.html" %}
<div class="alert alert-info">
	<p>To get started, select the Lok Sabha Seat below. </p>
</div>
<div class="container">
	<div class="row">
		<div class="list-group">
			{% if ls_seats_list %}
		    	{% for LokSabhaSeat in ls_seats_list %}
		        	<a href="{% url 'electoral_data.views.assembly' LokSabhaSeat.id %}" class="list-group-item">{{ LokSabhaSeat.name }} <span class="glyphicon glyphicon-chevron-right pull-right"></span></a>
		    	{% endfor %}
			{% else %}
		    	<p>No LS seats are available.</p>
			{% endif %}
		</div>
	</div>
</div>
{% include "electoral_data/footer.html" %}

electoral_data/templates/electoral_data/part.html
{% include "electoral_data/header.html" %}
<div class="alert alert-info">
    <p>Choose the Part no below below</p>
</div>
{% if part_no_list %}
<div class="table">
	<table class="table table-bordered table-hover">
		<thead>
			<th>Part No</th>
			<th>No. of citizens</th>
		</thead>
		<tbody>
			{% for Part in part_no_list %}
					<tr>
						<td>
				<a href="{% url 'electoral_data.views.citizens' part_no=Part.part_no polling_station_id=Part.polling_station %}" class="list-group-item">
							{{Part.part_no}}
				</a>
						</td>
						<td>
				<a href="{% url 'electoral_data.views.citizens' part_no=Part.part_no polling_station_id=Part.polling_station %}" class="list-group-item">
							{{Part.num_part}}
						</td>
				</a>
					</tr>
			{% endfor %}
		</tbody>
	</table>
</div>
{% else %}
    <p>No LS seats are available.</p>
{% endif %}
{% include "electoral_data/footer.html" %}

electoral_data/templates/electoral_data/polling.html
{% include "electoral_data/header.html" %}
<div class="alert alert-info">
    <p>Choose the Polling Station below</p>
</div>
<div class="container">
	<div class="row">
		<div class="list-group">
			{% if polling_list %}
			    {% for PollingStation in polling_list %}
			    	<a href="{% url 'electoral_data.views.part' PollingStation.id %}" class="list-group-item">{{ PollingStation.name | title }} <span class="glyphicon glyphicon-chevron-right pull-right"></span></a>
			    {% endfor %}
			{% else %}
			    <p>No LS seats are available.</p>
			{% endif %}
		</div>
	</div>
</div>
{% include "electoral_data/footer.html" %}

electoral_data/templates/electoral_data/society.html
{% include "electoral_data/header.html" %}
<h3>{{polling_station.name | title}}</h3>
<div class="alert alert-info">
    <p>Choose the Society below</p>
</div>
{% if societies_list %}
<div class="table">
	<table class="table table-bordered table-hover">
		<thead>
			<th>Society no</th>
			<th>Society Address</th>
		</thead>
		<tbody>
			{% for Society in societies_list %}
				{% if Society.processed %}
					<tr class="clickableRow success" href="{% url 'electoral_data.views.citizens' Society.society_no %}/">
				{% else %}
					<tr class="clickableRow" href="{% url 'electoral_data.views.citizens' Society.society_no %}">
				{% endif %}
						<td>{{Society.society_no}}</td>
						<td>{{Society.address | title}}</td>
					</tr>
			{% endfor %}
		</tbody>
	</table>
</div>
{% else %}
    <p>No LS seats are available.</p>
{% endif %}
{% include "electoral_data/footer.html" %}